services:
  - type: web
    name: svg-to-3d-api
    env: node
    plan: free
    nodeVersion: 20
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
